const FORMS={
'Guide':[['Présentation','textarea','Présentez-vous et expliquez votre parcours.'],['Pourquoi Guide ?','textarea','Pourquoi souhaitez-vous devenir Guide sur Lumalia ?'],['Connaissance de Lumalia','textarea','Que connaissez-vous de Lumalia et de Crystal ?'],['Disponibilités','text','Ex. mercredi après-midi, week-end…']],
'Modérateur':[['Présentation','textarea','Présentez-vous et votre expérience en modération.'],['Gestion d’un conflit','textarea','Comment réagiriez-vous face à un conflit entre deux joueurs ?'],['Sanctions','textarea','Comment détermineriez-vous une sanction adaptée ?'],['Disponibilités','text','Indiquez vos disponibilités.']],
'Builder':[['Présentation','textarea','Présentez votre expérience en construction.'],['Style et spécialités','textarea','Quels styles maîtrisez-vous ? Quels sont vos points forts ?'],['Portfolio','text','Lien vers vos constructions / portfolio.'],['Disponibilités','text','Indiquez vos disponibilités.']],
'Voix Off':[['Présentation','textarea','Présentez votre expérience en voix off.'],['Matériel','textarea','Quel matériel utilisez-vous ?'],['Portfolio audio','text','Lien vers des exemples audio.'],['Motivation','textarea','Pourquoi rejoindre la COM Lumalia Crystal ?']],
'Monteur':[['Présentation','textarea','Présentez votre expérience en montage vidéo.'],['Logiciels','text','Premiere Pro, DaVinci Resolve, After Effects…'],['Portfolio','text','Lien vers votre portfolio.'],['Motivation','textarea','Pourquoi rejoindre la COM Lumalia Crystal ?']],
'Développeur Java':[['Présentation','textarea','Présentez votre expérience en développement Java.'],['Compétences','textarea','Java, Paper, Spigot, Fabric, Forge, APIs, bases de données…'],['Projets / GitHub','text','Lien GitHub ou portfolio.'],['Expérience Minecraft','textarea','Décrivez vos projets Minecraft et plugins/mods.'],['Motivation','textarea','Pourquoi développer pour Lumalia ?']],
'Développeur Bedrock':[['Présentation','textarea','Présentez votre expérience en développement Bedrock.'],['Technologies','textarea','Décrivez les langages, APIs, moteurs ou outils que vous maîtrisez.'],['Projets / GitHub','text','Lien GitHub ou portfolio.'],['Expérience Bedrock','textarea','Décrivez vos projets Bedrock.'],['Motivation','textarea','Pourquoi Lumalia Bedrock ?']],
'Graphiste / UI Designer':[['Présentation','textarea','Présentez votre expérience en graphisme / UI.'],['Logiciels','text','Photoshop, Illustrator, Figma, Blender…'],['Portfolio','text','Lien vers votre portfolio.'],['Expérience UI/UX','textarea','Décrivez votre expérience en interface et expérience utilisateur.'],['Motivation','textarea','Pourquoi Lumalia ?']]
};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
document.addEventListener('DOMContentLoaded',()=>{
const session=getSession(); if(!session){location.href='connexion.html?redirect=candidature';return}
const params=new URLSearchParams(location.search),server=params.get('server')||'',job=params.get('job')||'';document.getElementById('appServer').textContent=server||'CANDIDATURE';document.getElementById('appTitle').textContent='Candidature — '+job;document.getElementById('appIntro').textContent='Prenez le temps de répondre avec précision. Les réponses sont transmises à l’équipe de recrutement.';
const fields=FORMS[job]||[['Présentation','textarea','Présentez-vous.'],['Motivation','textarea','Pourquoi souhaitez-vous rejoindre Lumalia ?']];
document.getElementById('dynamicFields').innerHTML='<div class="field-grid">'+fields.map((f,i)=>`<label class="${f[1]==='textarea'?'field-full':''}">${esc(f[0])} <span class="required">*</span>${f[1]==='textarea'?`<textarea name="q${i}" placeholder="${esc(f[2])}" required></textarea>`:`<input name="q${i}" placeholder="${esc(f[2])}" required>`}</label>`).join('')+'</div>';
document.getElementById('applicationForm').addEventListener('submit',e=>{e.preventDefault();const answers={};fields.forEach((f,i)=>answers[f[0]]=new FormData(e.target).get('q'+i));const applications=JSON.parse(localStorage.getItem('lumalia_jobs_applications')||'[]');applications.push({id:crypto.randomUUID(),userId:session.id,username:session.username,email:session.email,server,job,answers,status:'pending',createdAt:new Date().toISOString()});localStorage.setItem('lumalia_jobs_applications',JSON.stringify(applications));const msg=document.getElementById('submitMessage');msg.textContent='✓ Candidature envoyée ! Elle est maintenant en attente de traitement.';msg.className='form-message success';e.target.querySelector('button[type=submit]').disabled=true});
});
