let currentFilter='all';
function loadApps(){return JSON.parse(localStorage.getItem('lumalia_jobs_applications')||'[]')}
function renderDashboard(){const list=document.getElementById('applicationsList'),apps=loadApps().filter(a=>currentFilter==='all'||a.status===currentFilter);document.getElementById('statTotal').textContent=loadApps().length;document.getElementById('statPending').textContent=loadApps().filter(a=>a.status==='pending').length;document.getElementById('statAccepted').textContent=loadApps().filter(a=>a.status==='accepted').length;document.getElementById('statRejected').textContent=loadApps().filter(a=>a.status==='rejected').length;
if(!apps.length){list.innerHTML='<div class="empty">Aucune candidature dans cette catégorie.</div>';return}
list.innerHTML=apps.map(a=>`<article class="application-card" data-id="${a.id}"><div class="top"><div><h3>${a.username} — ${a.job}</h3><p>${a.server} • ${new Date(a.createdAt).toLocaleString('fr-FR')}</p></div><span class="status ${a.status}">${a.status==='pending'?'EN ATTENTE':a.status==='accepted'?'ACCEPTÉE':'REFUSÉE'}</span></div><div class="detail hidden">${Object.entries(a.answers).map(([q,v])=>`<div class="answer"><b>${q}</b><p>${String(v).replace(/</g,'&lt;')}</p></div>`).join('')}${a.status==='pending'?`<div class="actions"><button class="accept" data-action="accepted">✓ Accepter</button><button class="reject" data-action="rejected">✕ Refuser</button></div>`:''}</div></article>`).join('');
list.querySelectorAll('.application-card').forEach(card=>card.addEventListener('click',e=>{if(e.target.dataset.action)return;card.querySelector('.detail').classList.toggle('hidden')}));
list.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();updateStatus(btn.closest('.application-card').dataset.id,btn.dataset.action)}))}
function updateStatus(id,status){const apps=loadApps(),a=apps.find(x=>x.id===id);if(!a)return;a.status=status;const notifications=JSON.parse(localStorage.getItem('lumalia_jobs_notifications')||'[]');notifications.push({id:crypto.randomUUID(),userId:a.userId,title:status==='accepted'?'Candidature acceptée':'Candidature refusée',message:`Votre candidature « ${a.job} — ${a.server} » a été ${status==='accepted'?'acceptée':'refusée'} par l’équipe de recrutement Lumalia.`,createdAt:new Date().toISOString()});localStorage.setItem('lumalia_jobs_applications',JSON.stringify(apps));localStorage.setItem('lumalia_jobs_notifications',JSON.stringify(notifications));renderDashboard()}
document.addEventListener('DOMContentLoaded',()=>{const s=getSession(),allowed=s&&(s.role==='administrateur'||s.role==='super-moderateur');if(!allowed){const m=document.getElementById('accessMessage');m.classList.remove('hidden');m.innerHTML='<strong>Accès refusé</strong><p>Le dashboard est réservé aux administrateurs et super-modérateurs.</p>';return}document.getElementById('dashboardContent').classList.remove('hidden');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderDashboard()});renderDashboard()});
